stages:
- name: End
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: echo End
timeout: 60
notification:
  recipients:
  - recipient: ayanendu.de@gmail.com
    notifier: c-mqvbv:n-7rxwb
  condition:
  - Success
  - Failed
