---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 4085
    # Port to forward to inside the pod
    targetPort: 8085
    # Port accessible outside cluster
    nodePort: 30085
  type: LoadBalancer
---